language: python
python:
  - "3.7"
install:
  - "pip3 install flake8"
  - "pip3 install pep8-naming"
before_script:
  - "flake8 ./implementation/*.py --ignore=E131 --select=E999,E1,E4,E70,E74,E9,W6,N801,N804,N805,N807,F"
script:
  - "bash ./implementation/autotest/runtest.sh" 
